"""Create a watermarked corpus in resumable, independently scheduled batches.

Examples:
    python -m src.data_creation.create_t_ws 3
    python -m src.data_creation.create_t_ws 1 \
        --config data/t_ws/config_qwen.json --limit 50
    python -m src.data_creation.create_t_ws --combine \
        --config data/t_ws/config_qwen.json

Batch numbers are one-indexed. A partial batch is checkpointed and resumes on
the next invocation. ``--limit`` is intended for a timing smoke test and limits
only the number of new texts generated by that invocation.
"""

import argparse
import hashlib
import json
import math
from pathlib import Path
import sys

sys.stdout.reconfigure(line_buffering=True)

from src.util.filereader import REPO_ROOT, load_abstracts, write_path_file_atomic


DEFAULT_CONFIG = "data/t_ws/config_llama.json"
DEFAULT_KEYS = "data/keys.json"
DEFAULT_OUTPUT_DIR = "data/t_ws/llama"
MANIFEST_SCHEMA_VERSION = 1


def _relative_path(value, argument_name):
    path = Path(value)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"{argument_name} must be a path inside the repository: {value}")
    return path


def _load_json(relative_path):
    path = REPO_ROOT / relative_path
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _sha256(relative_path):
    return hashlib.sha256((REPO_ROOT / relative_path).read_bytes()).hexdigest()


def _settings(config_path, keys_path, output_dir_override):
    config_path = _relative_path(config_path, "--config")
    config = _load_json(config_path)
    keys_value = keys_path or config.get("keys_file", DEFAULT_KEYS)
    output_value = output_dir_override or config.get("output_dir", DEFAULT_OUTPUT_DIR)
    keys_path = _relative_path(keys_value, "--keys")
    output_dir = _relative_path(output_value, "--output-dir")

    n_samples = int(config["n_samples"])
    batch_size = int(config["batch_size"])
    if n_samples <= 0 or batch_size <= 0:
        raise ValueError("n_samples and batch_size must both be positive")

    return {
        "config": config,
        "config_path": config_path,
        "config_sha256": _sha256(config_path),
        "keys_path": keys_path,
        "keys_sha256": _sha256(keys_path),
        "output_dir": output_dir,
        "n_samples": n_samples,
        "batch_size": batch_size,
    }


def _batch_bounds(batch_num, n_samples, batch_size):
    n_batches = math.ceil(n_samples / batch_size)
    if batch_num == -1:
        return 0, n_samples
    if not 1 <= batch_num <= n_batches:
        raise ValueError(
            f"batch_num must be -1 or in [1, {n_batches}] "
            f"(batch_size={batch_size}, n_samples={n_samples}); got {batch_num}"
        )
    start = (batch_num - 1) * batch_size
    return start, min(start + batch_size, n_samples)


def _batch_dir(output_dir, start, end):
    return output_dir / f"t_ws_batch_samples_{start}_to_{end - 1}"


def _manifest(settings, start, end):
    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "config_file": str(settings["config_path"]),
        "config_sha256": settings["config_sha256"],
        "keys_file": str(settings["keys_path"]),
        "keys_sha256": settings["keys_sha256"],
        "watermark_model": settings["config"]["watermark_model"],
        "start_index": start,
        "end_index_exclusive": end,
        "expected_count": end - start,
    }


def _validate_or_write_manifest(batch_dir, expected):
    manifest_path = REPO_ROOT / batch_dir / "manifest.json"
    if manifest_path.exists():
        with manifest_path.open("r", encoding="utf-8") as f:
            existing = json.load(f)
        mismatches = {
            key: (existing.get(key), value)
            for key, value in expected.items()
            if existing.get(key) != value
        }
        if mismatches:
            details = ", ".join(
                f"{key}: existing={old!r}, requested={new!r}"
                for key, (old, new) in mismatches.items()
            )
            raise ValueError(
                f"Refusing to resume incompatible batch {batch_dir}: {details}"
            )
    else:
        write_path_file_atomic(list(batch_dir.parts), "manifest.json", expected)


def create(batch_num, settings, limit=None):
    from src.util.watermark import watermark

    config = settings["config"]
    n_samples = settings["n_samples"]
    batch_size = settings["batch_size"]
    start, end = _batch_bounds(batch_num, n_samples, batch_size)
    if limit is not None and limit <= 0:
        raise ValueError("--limit must be positive")

    keys = _load_json(settings["keys_path"])
    ids = keys.get("ids", [])
    k_ps = keys.get("k_ps", [])
    if len(ids) < n_samples or len(k_ps) < n_samples:
        raise ValueError(
            f"Keys file has {len(ids)} ids and {len(k_ps)} k_ps, but "
            f"the config requires {n_samples} of each"
        )

    T_os = load_abstracts(n_samples)
    if len(T_os) != n_samples:
        raise ValueError(
            f"Dataset contains only {len(T_os)} abstracts; expected {n_samples}"
        )

    batch_dir = _batch_dir(settings["output_dir"], start, end)
    manifest = _manifest(settings, start, end)
    _validate_or_write_manifest(batch_dir, manifest)

    print(
        f"Batch range [{start}, {end}); {end - start} texts; "
        f"output={batch_dir}"
    )
    watermark(
        T_os[start:end],
        ids[start:end],
        k_ps[start:end],
        config,
        experiment_path=list(batch_dir.parts),
        return_sts_scores=False,
        resume=True,
        checkpoint_every=int(config.get("checkpoint_every", 100)),
        progress_metadata=manifest,
        max_new_texts=limit,
    )


def combine(settings):
    """Validate and combine a complete set of non-overlapping batch outputs."""
    combined = []
    n_samples = settings["n_samples"]
    batch_size = settings["batch_size"]
    n_batches = math.ceil(n_samples / batch_size)

    for batch_num in range(1, n_batches + 1):
        start, end = _batch_bounds(batch_num, n_samples, batch_size)
        batch_dir = _batch_dir(settings["output_dir"], start, end)
        expected_manifest = _manifest(settings, start, end)
        manifest_path = REPO_ROOT / batch_dir / "manifest.json"
        texts_path = REPO_ROOT / batch_dir / "watermarked_texts.json"
        if not manifest_path.is_file() or not texts_path.is_file():
            raise FileNotFoundError(
                f"Batch {batch_num} is incomplete: expected {manifest_path} and {texts_path}"
            )
        _validate_or_write_manifest(batch_dir, expected_manifest)
        with texts_path.open("r", encoding="utf-8") as f:
            texts = json.load(f)
        expected_count = end - start
        if not isinstance(texts, list) or len(texts) != expected_count:
            raise ValueError(
                f"Batch {batch_num} contains "
                f"{len(texts) if isinstance(texts, list) else 'non-list data'}; "
                f"expected {expected_count}"
            )
        combined.extend(texts)
        print(f"Validated batch {batch_num}/{n_batches}: {expected_count} texts")

    if len(combined) != n_samples:
        raise AssertionError(f"Combined {len(combined)} texts, expected {n_samples}")
    output_parts = list(settings["output_dir"].parts)
    write_path_file_atomic(output_parts, "combined_t_ws.json", combined)
    write_path_file_atomic(
        output_parts,
        "combined_manifest.json",
        {
            **_manifest(settings, 0, n_samples),
            "batch_size": batch_size,
            "batch_count": n_batches,
            "combined_count": len(combined),
        },
    )
    print(
        f"Done. {len(combined)} texts saved to "
        f"{settings['output_dir'] / 'combined_t_ws.json'}"
    )


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "batch_num",
        nargs="?",
        type=int,
        default=-1,
        help="one-indexed batch; -1 (default) processes the whole corpus",
    )
    parser.add_argument("--config", default=DEFAULT_CONFIG)
    parser.add_argument(
        "--keys",
        default=None,
        help="override the keys file (otherwise use config keys_file or data/keys.json)",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="override the output directory from the config",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="generate at most this many new texts, then checkpoint and stop",
    )
    parser.add_argument(
        "--combine",
        action="store_true",
        help="validate and merge all completed batches instead of watermarking",
    )
    args = parser.parse_args()
    settings = _settings(args.config, args.keys, args.output_dir)
    if args.combine:
        if args.limit is not None:
            parser.error("--limit cannot be used with --combine")
        combine(settings)
    else:
        create(args.batch_num, settings, args.limit)


if __name__ == "__main__":
    main()
